# Generated by Django 5.1.6 on 2026-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_registro_huella',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='huella_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la huella digital', null=True, upload_to='huellas/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='huella_registrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='huella_template',
            field=models.BinaryField(blank=True, help_text='Template biométrico de la huella', null=True),
        ),
    ]
