# Generated by Django 5.1.6 on 2026-01-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_nino_tutor_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacceso',
            name='nino',
        ),
        migrations.RemoveField(
            model_name='registroacceso',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Nino',
        ),
        migrations.DeleteModel(
            name='RegistroAcceso',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
