# Generated by Django 5.1.6 on 2026-01-21 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_registroacceso_nino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADMIN', 'Administrador'), ('OBSERVADOR', 'Observador'), ('EMPLEADO', 'Empleado')], help_text='Nombre del rol en el sistema', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de las funciones del rol', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Perfil de Trabajador', 'verbose_name_plural': 'Perfiles de Trabajadores'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True, help_text='Usuario activo en el sistema'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la institución', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_registro_huella',
            field=models.DateTimeField(blank=True, help_text='Fecha de registro de huella', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='huella_registrada',
            field=models.BooleanField(default=False, help_text='Indica si tiene huella registrada'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones sobre el usuario', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Número de empleado institucional', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, help_text='Puesto en la institución', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección completa', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(help_text='Usuario de Django asociado', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol asignado al usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='login.rol'),
        ),
    ]
