# Generated by Django 5.1.6 on 2026-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rol_alter_perfil_options_perfil_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
