# Generated by Django 5.1.6 on 2026-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_escalamiento',
            field=models.CharField(blank=True, help_text='Código de 4 dígitos hasheado para autorizar salidas de emergencia', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_usar_codigo_escalamiento',
            field=models.BooleanField(default=False, help_text='Habilitado por el administrador para usar salidas de emergencia'),
        ),
    ]
