# Generated by Django 5.1.6 on 2026-01-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ninos/')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, help_text='Ej: O+, A-, AB+', max_length=5, null=True)),
                ('grupo', models.CharField(blank=True, help_text='Grupo o salón', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del tutor', max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_identificacion', models.CharField(choices=[('INE', 'INE/IFE'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA', 'Licencia de Conducir'), ('OTRO', 'Otro')], default='INE', max_length=20)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('TUTOR', 'Tutor Legal'), ('OTRO', 'Otro')], max_length=20)),
                ('huella_template', models.BinaryField(blank=True, help_text='Template biométrico de la huella', null=True)),
                ('huella_imagen', models.ImageField(blank=True, null=True, upload_to='huellas_tutores/')),
                ('huella_registrada', models.BooleanField(default=False)),
                ('fecha_registro_huella', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Tutor autorizado para recoger niños')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el tutor', null=True)),
            ],
            options={
                'verbose_name': 'Tutor Autorizado',
                'verbose_name_plural': 'Tutores Autorizados',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('verificacion_exitosa', models.BooleanField(default=True)),
                ('metodo_verificacion', models.CharField(default='HUELLA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='guarderia.nino')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_guardados', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='guarderia.tutor')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='nino',
            name='tutores',
            field=models.ManyToManyField(help_text='Tutores autorizados a recoger este niño', related_name='ninos', to='guarderia.tutor'),
        ),
    ]
