# Generated by Django 5.1.6 on 2026-01-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['dependencia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='tutor',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='es_trabajador',
            field=models.BooleanField(default=False, help_text='¿Es trabajador de gobierno?'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='estatus_laboral',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='referencias',
            field=models.TextField(blank=True, help_text='Referencias para llegar', null=True),
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(db_index=True, max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_asentamiento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'ordering': ['codigo_postal', 'nombre'],
                'unique_together': {('codigo_postal', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='colonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guarderia.colonia'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='guarderia.departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='guarderia.dependencia'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='guarderia.dependencia'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('dependencia', 'nombre')},
        ),
    ]
