# Generated by Django 5.1.6 on 2026-01-20 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0002_departamento_dependencia_remove_tutor_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio Médico',
                'verbose_name_plural': 'Servicios Médicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='numero_seguro_social',
            field=models.CharField(blank=True, help_text='Número de seguro social (NSS)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Grupo A, Sala 1', max_length=100)),
                ('tipo', models.CharField(choices=[('LACTANTE', 'Lactante'), ('MATERNAL', 'Maternal'), ('PREESCOLAR', 'Preescolar')], max_length=20)),
                ('grado', models.CharField(help_text='Ej: 1er año, 2do año', max_length=50)),
                ('capacidad_maxima', models.PositiveIntegerField(default=20, help_text='Número máximo de niños')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['tipo', 'grado', 'nombre'],
                'unique_together': {('nombre', 'tipo', 'grado')},
            },
        ),
        migrations.AlterField(
            model_name='nino',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo al que pertenece el niño', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninos', to='guarderia.grupo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='servicio_medico',
            field=models.ForeignKey(blank=True, help_text='Servicio médico del tutor (ISSSTE, IMSS, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores', to='guarderia.serviciomedico'),
        ),
        migrations.CreateModel(
            name='ObservacionNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('CONDUCTA', 'Conducta'), ('SALUD', 'Salud'), ('HIGIENE', 'Higiene'), ('MATERIAL', 'Material/Uniforme'), ('ALIMENTACION', 'Alimentación'), ('ACADEMICO', 'Académico'), ('OTRO', 'Otro')], default='GENERAL', help_text='Tipo de observación', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la observación')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la observación')),
                ('hora', models.TimeField(auto_now_add=True, help_text='Hora de registro')),
                ('importante', models.BooleanField(default=False, help_text='Marcar si requiere atención especial')),
                ('notificar_tutor', models.BooleanField(default=False, help_text='Si se debe notificar al tutor')),
                ('notificado', models.BooleanField(default=False, help_text='Si ya se notificó al tutor')),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se notificó', null=True)),
                ('nino', models.ForeignKey(help_text='Niño al que se refiere la observación', on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='guarderia.nino')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario que registró la observación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['nino', '-fecha'], name='guarderia_o_nino_id_63bf0c_idx'), models.Index(fields=['fecha', 'importante'], name='guarderia_o_fecha_497387_idx')],
            },
        ),
    ]
