# Generated by Django 5.1.6 on 2026-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0003_serviciomedico_tutor_numero_seguro_social_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colonia',
            options={'ordering': ['d_codigo', 'd_asenta'], 'verbose_name': 'Colonia', 'verbose_name_plural': 'Colonias'},
        ),
        migrations.AlterUniqueTogether(
            name='colonia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='colonia',
            name='D_mnpio',
            field=models.CharField(default='Sin municipio', max_length=200, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='c_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Clave Estado'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='c_mnpio',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Clave Municipio'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='c_oficina',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Clave Oficina'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='c_tipo_asenta',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Clave Tipo Asentamiento'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_CP',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CP Oficina Postal'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_asenta',
            field=models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre del Asentamiento'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_codigo',
            field=models.CharField(db_index=True, default='00000', max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_estado',
            field=models.CharField(default='Sin estado', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='d_tipo_asenta',
            field=models.CharField(default='Colonia', max_length=50, verbose_name='Tipo de Asentamiento'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='colonia',
            name='id_asenta_cpcons',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='ID Único'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['d_codigo'], name='guarderia_c_d_codig_41c42a_idx'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['d_codigo', 'd_asenta'], name='guarderia_c_d_codig_2a21e3_idx'),
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='tipo_asentamiento',
        ),
    ]
