# Generated by Django 5.1.6 on 2026-01-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0004_alter_colonia_options_alter_colonia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='id_asenta_cpcons',
            field=models.CharField(db_index=True, default='0', max_length=20, verbose_name='ID Único'),
        ),
    ]
