# Generated by Django 5.1.6 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0005_alter_colonia_id_asenta_cpcons'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Género del niño', max_length=1),
        ),
        migrations.AddField(
            model_name='nino',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
