# Generated by Django 5.1.6 on 2026-04-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0006_nino_genero_nino_numero_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGuarderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Guardería', max_length=200)),
                ('tiempo_minimo_entre_registros', models.PositiveIntegerField(default=30, help_text='Minutos que deben pasar entre una entrada y una salida, o viceversa, para el mismo niño.', verbose_name='Tiempo mínimo entre registros (minutos)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Guardería',
                'verbose_name_plural': 'Configuración de Guardería',
            },
        ),
    ]
