# Generated by Django 5.1.6 on 2026-04-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0007_configuracionguarderia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Tutor que acompañó. Puede ser nulo en salidas de emergencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='guarderia.tutor'),
        ),
    ]
