# Generated by Django 5.1.6 on 2026-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0007_configuracionguarderia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonia',
            name='c_estado',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='c_mnpio',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='c_oficina',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='c_tipo_asenta',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='d_CP',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='d_ciudad',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='d_tipo_asenta',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='id_asenta_cpcons',
        ),
    ]
