# Generated by Django 5.1.6 on 2026-04-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0008_add_codigo_escalamiento_y_tutor_nullable'),
        ('guarderia', '0008_remove_colonia_c_estado_remove_colonia_c_mnpio_and_more'),
    ]

    operations = [
    ]
