# Generated by Django 5.1.6 on 2026-07-21 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0011_observacionnino_area_recurrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Descripción del motivo de la amonestación', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Detalle adicional opcional')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amonestación',
                'verbose_name_plural': 'Amonestaciones',
                'ordering': ['motivo'],
            },
        ),
        migrations.CreateModel(
            name='AmonestacionNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se aplicó la amonestación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas adicionales opcionales')),
                ('amonestacion', models.ForeignKey(help_text='Amonestación del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='guarderia.amonestacion')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones', to='guarderia.nino')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amonestaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amonestación de Niño',
                'verbose_name_plural': 'Amonestaciones de Niños',
                'ordering': ['-fecha', '-fecha_registro'],
                'indexes': [models.Index(fields=['nino', '-fecha'], name='amon_nino_fecha_idx')],
            },
        ),
    ]
