# Generated by Django 5.1.6 on 2026-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0012_amonestacion_amonestacionnino'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='fecha_graduacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='graduado',
            field=models.BooleanField(default=False),
        ),
    ]
