# Generated by Django 5.1.6 on 2026-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0013_nino_fecha_graduacion_nino_graduado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('INE', 'INE/IFE'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA', 'Licencia de Conducir'), ('OTRO', 'Otro')], default='INE', max_length=20),
        ),
    ]
