# Generated by Django 5.1.6 on 2026-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderia', '0014_alter_tutor_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionguarderia',
            name='siguiente_matricula',
            field=models.PositiveIntegerField(default=2601, verbose_name='Siguiente número de matrícula'),
        ),
    ]
